spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/e_store?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: sunboyu123
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
erupt-app:
  water-mark: false